spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ebt?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:ebt}
    password: ${DB_PASSWORD:ebt01}

