spring:
  config:
    activate:
      on-profile: test
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ebt?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:ebt}
    password: ${DB_PASSWORD:ebt01}

