package com.krdevops.springai.model.contract;

/** 5축 파이프라인 발전 계약에서 API·MCP·검증기가 공유하는 안정적인 오류 코드. */
public enum PipelineEvolutionErrorCode {
    DESIGN_EVIDENCE_MISSING,
    DESIGN_CONFIDENCE_TOO_LOW,
    DESIGN_SYSTEM_SNAPSHOT_STALE,
    COMPONENT_MAPPING_MISSING,
    RENDERER_CAPABILITY_UNSUPPORTED,
    GENERATION_DEPENDENCY_UNRESOLVED,
    OWNERSHIP_CONFLICT,
    EVIDENCE_REVISION_MISMATCH,
    REVIEW_EVIDENCE_CHANGED,
    HANDOFF_ACTION_NOT_ALLOWED,
    PROTOTYPE_SECRET_DETECTED,
    ARTIFACT_REFERENCE_MISMATCH
}
