CREATE TABLE IF NOT EXISTS AI_FIGMA_REFINEMENT_SET (
    PATCH_SET_ID VARCHAR(64) NOT NULL,
    SCREEN_ID VARCHAR(64) NOT NULL,
    BASE_SCREEN_VERSION INT NOT NULL,
    BASE_MATERIALIZATION_HASH VARCHAR(128) NOT NULL,
    REFINEMENT_STATUS VARCHAR(32) NOT NULL,
    CAPTURED_AT DATETIME(6) NOT NULL,
    APPROVED_AT DATETIME(6),
    APPROVED_BY VARCHAR(128),
    APPROVAL_COMMENT VARCHAR(2000),
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (PATCH_SET_ID),
    INDEX IDX_FIGMA_REFINEMENT_SET_SCREEN (SCREEN_ID, BASE_SCREEN_VERSION, REFINEMENT_STATUS)
);

CREATE TABLE IF NOT EXISTS AI_FIGMA_REFINEMENT_PATCH (
    PATCH_SET_ID VARCHAR(64) NOT NULL,
    PATCH_INDEX INT NOT NULL,
    LOGICAL_NODE_ID VARCHAR(512) NOT NULL,
    BASELINE_LOGICAL_TYPE VARCHAR(128) NOT NULL,
    PROPERTY_PATH VARCHAR(128) NOT NULL,
    PROPERTY_TYPE VARCHAR(16) NOT NULL,
    BEFORE_VALUE_JSON TEXT,
    AFTER_VALUE_JSON TEXT,
    PATCH_OWNER VARCHAR(32) NOT NULL,
    PATCH_SCOPE VARCHAR(16) NOT NULL,
    CONFLICT_STATUS VARCHAR(32) NOT NULL DEFAULT 'NONE',
    PRIMARY KEY (PATCH_SET_ID, PATCH_INDEX),
    INDEX IDX_FIGMA_REFINEMENT_PATCH_NODE (PATCH_SET_ID, LOGICAL_NODE_ID)
);
