CREATE TABLE AI_COMPONENT_REGISTRY_V3 (
    PROFILE_ID       VARCHAR(64)  NOT NULL,
    REGISTRY_VERSION VARCHAR(32)  NOT NULL,
    CATALOG_VERSION  VARCHAR(32)  NOT NULL,
    SCHEMA_VERSION   VARCHAR(64)  NOT NULL,
    SOURCE_REVISION  VARCHAR(128) NOT NULL,
    APPROVED_BY      VARCHAR(128) DEFAULT NULL,
    APPROVED_AT      DATETIME(6)  DEFAULT NULL,
    CONTENT_HASH     CHAR(64)     NOT NULL,
    REGISTRY_JSON    LONGTEXT     NOT NULL,
    CREATED_AT       DATETIME(6)  DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (PROFILE_ID, REGISTRY_VERSION),
    KEY IDX_COMPONENT_REGISTRY_V3_CATALOG (CATALOG_VERSION),
    KEY IDX_COMPONENT_REGISTRY_V3_APPROVED (PROFILE_ID, APPROVED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
