CREATE TABLE IF NOT EXISTS AI_COMPONENT_REGISTRY_RESOLUTION_REPORT (
    REPORT_ID VARCHAR(64) PRIMARY KEY,
    PROFILE_ID VARCHAR(128) NOT NULL,
    LEGACY_REGISTRY_VERSION VARCHAR(64) NOT NULL,
    RESOLVED_REGISTRY_VERSION VARCHAR(64) NOT NULL,
    COMPARED_AT TIMESTAMP NOT NULL,
    IDENTICAL BOOLEAN NOT NULL,
    REPORT_JSON JSON NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
