CREATE TABLE AI_DESIGN_CODE_COMPONENT_MAPPING (
    MAPPING_ID             VARCHAR(64)  NOT NULL,
    MAPPING_VERSION        VARCHAR(32)  NOT NULL,
    MAPPING_STATUS         VARCHAR(32)  NOT NULL,
    LOGICAL_TYPE           VARCHAR(128) NOT NULL,
    FIGMA_COMPONENT_SET_KEY VARCHAR(128) NOT NULL,
    THYMELEAF_FRAGMENT     VARCHAR(512) NOT NULL,
    SOURCE_REVISION        VARCHAR(128) NOT NULL,
    APPROVED_BY            VARCHAR(128) DEFAULT NULL,
    APPROVED_AT            DATETIME(6)  DEFAULT NULL,
    CONTENT_HASH           CHAR(64)     NOT NULL,
    MAPPING_JSON           LONGTEXT     NOT NULL,
    CREATED_AT             DATETIME(6)  DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (MAPPING_ID, MAPPING_VERSION),
    KEY IDX_DESIGN_CODE_MAPPING_LOGICAL_STATUS (LOGICAL_TYPE, MAPPING_STATUS, APPROVED_AT),
    KEY IDX_DESIGN_CODE_MAPPING_FIGMA_KEY (FIGMA_COMPONENT_SET_KEY),
    KEY IDX_DESIGN_CODE_MAPPING_CONTENT_HASH (CONTENT_HASH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
