CREATE TABLE AI_GENERATION_OPERATION_AUDIT (
    AUDIT_ID             VARCHAR(64)  NOT NULL,
    OPERATION_ID         VARCHAR(64)  NOT NULL,
    OPERATION_REVISION   INT          NOT NULL,
    PROJECT_ROOT         VARCHAR(1024),
    TABLE_NAME           VARCHAR(128),
    SCREEN_ID            VARCHAR(256),
    CALLER_TYPE          VARCHAR(64),
    ACTOR_ID             VARCHAR(128),
    ENVIRONMENT_NAME     VARCHAR(64),
    CHANGED_REGIONS_JSON LONGTEXT     NOT NULL,
    PRESERVED_REGIONS_JSON LONGTEXT   NOT NULL,
    CONFLICT_REGIONS_JSON LONGTEXT    NOT NULL,
    CHANGED_FILES_JSON   LONGTEXT     NOT NULL,
    STATUS               VARCHAR(32)  NOT NULL,
    FAILURE_STAGE        VARCHAR(64),
    FAILURE_DETAIL       LONGTEXT,
    CREATED_AT           DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (AUDIT_ID),
    KEY IX_GEN_AUDIT_OPERATION (OPERATION_ID, OPERATION_REVISION),
    KEY IX_GEN_AUDIT_STATUS (STATUS, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AI_GENERATION_VALIDATION_EVIDENCE (
    EVIDENCE_ID       VARCHAR(64)  NOT NULL,
    OPERATION_ID      VARCHAR(64)  NOT NULL,
    GATE_TYPE         VARCHAR(32)  NOT NULL,
    STATUS            VARCHAR(32)  NOT NULL,
    SEVERITY          VARCHAR(16)  NOT NULL,
    INPUT_REFS_JSON   LONGTEXT     NOT NULL,
    OUTPUT_REFS_JSON  LONGTEXT     NOT NULL,
    CONTENT_HASH      VARCHAR(128),
    SOURCE_REVISION   VARCHAR(128),
    VALIDATOR_VERSION VARCHAR(64),
    CREATED_AT        DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (EVIDENCE_ID),
    KEY IX_GEN_EVIDENCE_OPERATION (OPERATION_ID, CREATED_AT),
    KEY IX_GEN_EVIDENCE_GATE (OPERATION_ID, GATE_TYPE, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
