CREATE TABLE AI_GENERATION_READINESS_COMPARISON (
    COMPARISON_ID             VARCHAR(64)  NOT NULL,
    OPERATION_ID              VARCHAR(64)  NOT NULL,
    SOURCE_TYPE               VARCHAR(32)  NOT NULL,
    LEGACY_READY              BOOLEAN      NOT NULL,
    COMMON_READY              BOOLEAN      NOT NULL,
    MATCHED                   BOOLEAN      NOT NULL,
    MISMATCH_REASON           VARCHAR(64),
    LEGACY_FAILED_GATES_JSON  LONGTEXT     NOT NULL,
    COMMON_FAILED_GATES_JSON  LONGTEXT     NOT NULL,
    COMMON_MISSING_GATES_JSON LONGTEXT     NOT NULL,
    CREATED_AT                DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (COMPARISON_ID),
    KEY IX_READINESS_COMPARISON_CREATED (CREATED_AT),
    KEY IX_READINESS_COMPARISON_REASON (MATCHED, MISMATCH_REASON, CREATED_AT),
    KEY IX_READINESS_COMPARISON_OPERATION (OPERATION_ID, SOURCE_TYPE, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
