-- ARCH-0414/0415: Thymeleaf ProjectOperation을 Figma AI_FIGMA_DESIGN_OPERATION과 같은 패턴
-- (revision 기반 불변 저장 + requestHash 멱등성 index)으로 영속화한다. 기존
-- ThymeleafProjectWorkflowService의 ConcurrentHashMap을 대체해 RISK-03(재시작 시 승인 작업
-- 소실)을 닫는다.

CREATE TABLE AI_THYMELEAF_PROJECT_OPERATION (
    OPERATION_ID     VARCHAR(64) NOT NULL,
    REVISION         INT         NOT NULL,
    STATUS           VARCHAR(32) NOT NULL,
    SNAPSHOT_JSON    LONGTEXT    NOT NULL,
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (OPERATION_ID, REVISION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AI_THYMELEAF_PROJECT_OPERATION_IDEMPOTENCY (
    PREVIEW_HASH     VARCHAR(128) NOT NULL,
    OPERATION_ID     VARCHAR(64)  NOT NULL,
    CREATED_AT       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PREVIEW_HASH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
