CREATE TABLE AI_OPERATION_EVENT (
 EVENT_ID VARCHAR(64) NOT NULL, OPERATION_ID VARCHAR(64) NOT NULL, OPERATION_TYPE VARCHAR(64) NOT NULL,
 REVISION INT NOT NULL, FROM_STATUS VARCHAR(64), TO_STATUS VARCHAR(64), EVENT_TYPE VARCHAR(64) NOT NULL,
 ACTOR VARCHAR(128) NOT NULL, CORRELATION_ID VARCHAR(128) NOT NULL, PAYLOAD_HASH VARCHAR(128),
 OCCURRED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (EVENT_ID),
 KEY IX_OPERATION_EVENT_OPERATION (OPERATION_ID, REVISION), KEY IX_OPERATION_EVENT_CORRELATION (CORRELATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AI_OPERATION_LOCK (
 LOCK_KEY VARCHAR(512) NOT NULL, OPERATION_ID VARCHAR(64) NOT NULL, OWNER_ID VARCHAR(128) NOT NULL,
 FENCING_TOKEN BIGINT NOT NULL, EXPIRES_AT DATETIME(6) NOT NULL, ACQUIRED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 PRIMARY KEY (LOCK_KEY), KEY IX_OPERATION_LOCK_EXPIRES (EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
