CREATE TABLE AI_PROJECT_ROOT_REGISTRY (
 PROJECT_ROOT VARCHAR(512) NOT NULL,
 REGISTERED_BY VARCHAR(128) NOT NULL,
 REGISTRATION_SOURCE VARCHAR(32) NOT NULL,
 REGISTERED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 PRIMARY KEY (PROJECT_ROOT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
