CREATE TABLE IF NOT EXISTS AI_VARIANT_RULE_SET (
    RULE_SET_ID VARCHAR(64) NOT NULL,
    RULE_SET_VERSION VARCHAR(32) NOT NULL,
    PROFILE_ID VARCHAR(64) NOT NULL,
    REGISTRY_VERSION VARCHAR(32) NOT NULL,
    RULE_SET_STATUS VARCHAR(32) NOT NULL,
    RULE_SET_JSON LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (RULE_SET_ID, RULE_SET_VERSION),
    KEY IDX_VARIANT_RULE_PROFILE (PROFILE_ID, REGISTRY_VERSION, RULE_SET_STATUS)
);

CREATE TABLE IF NOT EXISTS AI_SCREEN_PATTERN (
    PATTERN_ID VARCHAR(64) NOT NULL,
    PATTERN_VERSION VARCHAR(32) NOT NULL,
    PATTERN_JSON LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (PATTERN_ID, PATTERN_VERSION)
);
