CREATE TABLE IF NOT EXISTS AI_FIGMA_LIBRARY_INVENTORY (
    PROFILE_ID VARCHAR(64) NOT NULL,
    REGISTRY_VERSION VARCHAR(64) NOT NULL,
    INVENTORY_VERSION VARCHAR(128) NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    CAPTURED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (PROFILE_ID, REGISTRY_VERSION, INVENTORY_VERSION),
    INDEX IDX_FIGMA_INVENTORY_LATEST (PROFILE_ID, REGISTRY_VERSION, CAPTURED_AT)
);
