ALTER TABLE AI_SCREEN_PATTERN
    ADD COLUMN PATTERN_STATUS VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED' AFTER PATTERN_VERSION;

CREATE INDEX IDX_SCREEN_PATTERN_STATUS
    ON AI_SCREEN_PATTERN (PATTERN_ID, PATTERN_STATUS, CREATED_AT);
